export const termsAndConditions = `
# Terms and Conditions

## ACCEPTANCE OF THE TERMS.
LAtA.ng Online Marketplace Nigeria Limited, its connected businesses (collectively referred to as "the Administrator," "we," or "us," and you as the "User") are bound by these Terms of Use (the "Terms"). Before using the LAtA.ng website, mobile applications, or any service, material, or data made accessible via them (collectively referred to as the "Service" or the "Platform"), we strongly advise you to read these Terms carefully. You consent to being bound by these Terms by accessing or using the Service. Do not access or use the Service if you disagree with any portion of these Terms or if you are not eligible or permitted to be bound by the Terms. We also advise you to read our Privacy Policy. You accept and agree to the terms of the Privacy Policy and any additional terms, rules, policies, or documents that may from time to time be placed on the Platform, and which are thus explicitly incorporated herein by reference, by accessing or using the Service. We retain the right to alter or modify these Terms at any time and for any cause, with or without previous notice to you, at our sole discretion.

## IMPORTANT DISCLAIMERS.
ALL SERVICES PROVIDED BY THE ADMINISTRATOR ARE DELIVERED "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS," AND THE  ADMINISTRATOR DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY GUARANTEES RELATING TO CONDITION, QUALITY, LIFE DURATION, PERFORMANCE, ACCURACY, RELIABILITY, OR AFFORDABILITY AND SUITABILITY FOR PARTICULAR PURPOSE. WE HEREBY DISCLAIMS ALL SUCH WARRANTIES AND LIABILITIES.

The administrator has no control over and makes no guarantees regarding the existence, quality, safety, or legality of the goods and services posted by users on the platform, the reliability or accuracy of the information provided by users in the announcements, the ability of sellers to sell goods or provide services, the capability of buyers to make payments for goods or services, or that a user will actually complete a
transaction. THE ADMINISTRATOR MAKES NO WARRANTIES REGARDING THE NON-INFRINGEMENT OF THIRD PARTY RIGHTS WITH RESPECT TO THE MANUFACTURING, IMPORTATION, EXPORTATION, OFFER, DISPLAYING, PURCHASE, SALE, ADVERTISING, AND/OR USE OF PRODUCTS OR SERVICES, WHICH ARE OFFERED OR DISPLAYED ON THE PLATFORM. The administrator therefore explicitly disclaims any LIABILITY RELATED TO CONTENT AND INFORMATION POSTED ON THE PLATFORM BY USERS. We advise you to inspect the goods before making a purchase and to ask the seller for documentation attesting to their compliance with all applicable laws, regulations, rules, guidelines, and standards. YOU ACKNOWLEDGE THAT YOU ALONE ARE RESPONSIBLE FOR YOUR SAFETY AND THAT YOU SHOULD MEET WITH OTHER PEOPLE ONLY IN SAFE PUBLIC PLACES DURING DAYLIGHT HOURS TO COMPLETE A TRANSACTION. YOUR SOLE RESPONSIBILITY IS TO PERFORM DUE DILIGENCE ON ANYONE OR ANY ORGANIZATION THAT REQUESTS A MEETING TO CONDUCT A JOB INTERVIEW OR TO COMPLETE A TRANSACTION. A USER'S INTERACTION WITH ANY PERSON OR ORGANIZATION IS NOT THE ADMINISTRATOR'S RESPONSIBILITY.

## ACCOUNT REGISTRATION
You must register an Account on the Platform in order to use some Service features. You will be prompted to provide some personal data on the registration form. Either as an individual or as an authorized representative of a firm, you may create an Account. Each user is only permitted to establish one Account. In order to avoid duplicate Accounts when many users visit the same device, we could request identification documentation. You are accountable for any action carried out using your Account access information and are responsible for keeping those data secret. By creating an account, you confirm and guarantee that you are of legal age to use the service or that a parent is watching over you. If you are a minor, your parent or legal guardian must read and accept these Terms before granting you permission to use the Service. The majority of governments consider users under the age of 18 to be children. If you breach these Terms, we have the right to suspend or cancel your Account or your access to the Service at any time, with or without warning. You must notify us right once if you detect any unauthorized use of your Account or any security breach. Failure to adhere to the aforementioned standards may result in loss or damage for which we are not responsible.

## SERVICE
Users can make and post announcements on the Platform, browse announcements made by other users, and get in touch with other users by utilizing the information supplied in the announcements' contact fields. The Administrator is not a producer, distributor, seller, importer, or manufacturer of any goods or services listed by users on the Platform. Furthermore, with regard to the marketing of any products or services posted on the Platform, the Administrator is neither a marketer nor a representative of users. The Administrator is not a party to the actual sale and purchase contracts or service agreements that are made directly between the users. The Administrator offers the users with a channel for communication. Any applicable taxes resulting from the sale of the goods or services listed on the Platform shall be the sole responsibility of the Users to collect and remit. The Administrator reserves the right to remove or restrict access to announcements made by users without prior notice in the following situations: (i) receiving mandatory judgments from public authorities; (ii) a claim from a person who owns intellectual property rights to stop a user from violating those rights on the Platform; (iii) violations of the legal rights or interests of other users, organizations, or people upon their reasonable request; (iv) determining that an individual has violated the law. Regardless of whether a user is given access to the necessary supporting documentation, the Administrator is permitted to delete or ban their announcements. Any modifications to the Service (whether to free or paid features) may be made at any time, with or without notice, by the Administrator. You
agree that the Administrator is not responsible or liable for any consequences of any such actions or results, including, without limitation, the deletion of, or the failure to make available to you, any content or services. You acknowledge that a variety of Administrator's actions may limit or prevent you from accessing the Service at specific times and/or in the same way, for temporary periods, or permanently. Each Service user is entirely accountable for all of his or her (As specified below) User Content. You understand and accept that we are not responsible for any User Content and that we do not guarantee its accuracy, currency, appropriateness, or quality. We further disclaim any liability with regard to any User Content because we have no control over it. There is no third party involved in any interactions you have with other Service users. You acknowledge and agree that the Administrator will not be held liable for any loss or harm arising from such interactions. We are under no duty to mediate disputes between you and other Service users. The "Third Party Ads" refer to ads for third parties and links to third-party websites or other resources that may be found on the Service. Such The Administrator has no control over any Third-Party Ads and is not accountable for any Third-Party Ads. These Third-Party Ads are simply provided by the Administrator as a convenience; no endorsement, approval, monitoring, warranty, or other statement regarding Third-Party Ads is made by the Administrator. Information given by web domains to which the Third Party Ads link may not be entirely accurate, including advertisements and other information. You accept full responsibility for using any such online properties and all associated risks. The terms and policies of the relevant service provider, including its privacy and data collection policies, apply when you link to third-party web domains. You should conduct whatever research you deem suitable or required before moving through with any transaction with any other person. You and the third party with whom you transact or otherwise interact in connection with any Third-Party Ads that you may encounter on or via the Service, including the payment and delivery of any connected products or services, are your only parties. You hereby waive any and all claims, demands, losses, damages, rights, claims, and actions of any kind, including bodily harm, wrongful death, and property damage, that are related to or result from any interactions with or behavior of any Service users or any Third Party Ads, whether directly or indirectly.

## ANNOUNCEMENTS POSTED BY USERS
Upon request from the Administrator, a user must give the Administrator any documentation attesting to the validity of announcements posted and identity documents. When a user publishes announcements regarding the sale of products or services on the platform, they must include accurate and comprehensive information about the items and services being sold as well as the terms and circumstances under which the services will be provided. The user's terms and conditions for the sale of goods and the supply of services shall not conflict with these Terms or any relevant legislation.The cost of the items or services must be precise. This information must be included in the announcement if it appears to have changed as a result of any particular circumstances. You consent to be governed by the YouTube Terms of Service, which are accessible at [https://www.youtube.com/t/terms](https://www.youtube.com/t/terms), when you upload a YouTube video to your announcement using the YouTube API Services capabilities made available by the Administrator. By using the Facebook Embedded Video & Live Player functionality provided by the Administrator to add a Facebook video to your announcement, you consent to be bound by the Facebook Terms of Service and the Meta Platform Terms, both of which are available at [https://developers.facebook.com/terms/](https://developers.facebook.com/terms/).

## FEES
The Platform is normally free, but it may also offer paid services. We could, for example, impose restrictions on the publication of announcements in specific categories or provide advertising choices for announcements on the Platform. If you utilize payable services on any of them, you are permitted to register more than one Account. On the Platform, we provide information on the fees we charge for utilizing pay-for-use services as well as the payment options we accept. The rates and accepted payment methods are subject to change at any moment and for any cause, in our sole discretion. The costs are non-refundable owing to the nature of online services, unless expressly stated otherwise by necessary provisions of the applicable legislation. Your service fees are subject to the terms and conditions of LATA.ng billing policy

## REPRESENTATIONS AND WARRANTIES OF THE USER
- By utilizing the Service, you affirm and promise that: You are of legal age and agree to abide by the Terms.
- If you sign up to use the Platform on behalf of a company, that business has given you permission to contract with us and other Platform users;You are older than 18 years old.
- You'll have given truthful, accurate, and comprehensive information on your Account, or you already have;
- To keep your Account's information true, accurate, and comprehensive, you must update it.
- If you suspect that your Account access information was revealed to or likely utilized by other parties, you shall immediately alter the data used to access the Platform.
- You'll let the Administrator know on time and You will ensure to keep your Account safe from any unauthorized access; You won't give any false or deceptive information about who you are or where you are.
- You shall strictly abide by all applicable laws, rules, regulations, and policies when using the Service.
- You won't utilize the Service for any improper or prohibited purposes.
- You won't publish any announcements on the Platform offering to buy, sell, or trade any Prohibited Items (see [https://LATA.ng/faq/14](https://LATA.ng/faq/14) for more information).
- You will not publish announcements on the Platform that violate another person's rights or interests, including any intellectual property rights or other third party personal or proprietary rights.
- An announcement that contains false, misleading, or deceptive assertions, as well as any personal or identifying information about children or other people without their consent, is not permitted to be posted on the platform. The promotion of hate, violence, discrimination, racism, xenophobia, or ethnic conflicts; pornographic, overtly sexual materials; depictions that encourage the illegal or careless use of weapons and dangerous objects, or make it easier to buy firearms or ammunition; defamatory, discriminatory, mean-spirited, threatening, or harassing materials; appeals to violence and unlawful behavior; offers of prostitution or other services. Unauthorized copies can include products that have been illegally obtained, stolen, or pirated; direct or indirect referrals to any other websites; and information about websites that compete with the the promotion of hate, violence, discrimination, racism, xenophobia, or ethnic conflicts; pornographic, overtly sexual materials; depictions that encourage the illegal or careless use of weapons and dangerous objects, or make it easier to buy firearms or ammunition; defamatory, discriminatory, mean-spirited, threatening, or harassing materials; appeals to violence and unlawful behavior; offers of prostitution or other services. Unauthorized copies can include products that have been illegally obtained, stolen, or pirated; direct or indirect referrals to any other websites; and information about websites that compete with the platform.
- You won't employ software or take any other activities that try to impede the Platform's usual operation.
- You won't use the Platform or any other method to advertise or disseminate unsolicited commercial emails, chain letters, or Ponzi schemes to other Platform users.
- Without the user's permission, you will not duplicate, edit, or distribute any other User Content.
- Without the users' consent, you must not harvest or otherwise gather user data, including email addresses and phone numbers, or infringe in any other way on their privacy.
- Worms, viruses, trojan horses, and other malware won't be downloaded, stored, posted, distributed, or used in any other manner.
- You are the rightful owner of the products listed as being for sale in your announcement, and you have the relevant LATA.ng RULES FOR CONTEST.
- The Company will apply a withholding tax on your award in accordance with the applicable rules of Nigerian tax law; as a result, you may receive your award minus the appropriate withholding tax. You are now notified and understand that the amount actually withheld by the
- Company may not be the whole amount of your federal, state, and local individual income taxes, as well as any other taxes linked to the award and lawfully applicable to you, which are ultimately your responsibility.

## RULES AND JURISDICTION FOR GOVERNMENT
The laws of the Republic of Nigeria shall apply to the interpretation and enforcement of these Terms. Arbitration pursuant to the Arbitration and Conciliation Act (Cap. A18) of the Republic of Nigeria may be used to settle any dispute arising out of or relating to these Terms, including any question about its existence, validity, or termination. There will only be one arbiter. The arbitration will take place in Abuja, Nigeria. English shall be the language of the arbitration proceedings.

## RIGHTS TO INTELLECTUAL PROPERTY
The Administrator makes no claim to ownership of the copyright or other proprietary intellectual property rights in the information you provide to us as part of your registration or any data, text, pictures, or other materials you may submit or post on the Platform (the "User Content"). These materials remain your intellectual property. Despite the aforementioned, you consent to the Administrator's right to keep copies of all registration data and user content and to use them as reasonably necessary for or incidental to the Service's operation and as outlined in these Terms and the Privacy Policy. Any issues that may arise will be between the users and not with us the administrators. Our responsibility is to accept users' information and publish it as provided.

Agreeing to use LATA.ng automatically means you have granted us full access to use whatever you submitted on the platform.

## CONTACT
You can reach us at [support@lata.ng](mailto:support@lata.ng) if you need to send any notices required by these Terms or if you have any queries about the Service.

## Updated on June 20, 2023

`
