const POSITIVE_FEEDBACK = "POSITIVE";
const NEUTRAL_FEEDBACK = "NEUTRAL";
const NEGATIVE_FEEDBACK = "NEGATIVE";

export const POSITIVE_FEEDBACK_RATING = 3;
export const NEUTRAL_FEEDBACK_RATING = 2;
export const NEGATIVE_FEEDBACK_RATING = 1;
