export const mainMetaDescription = `GET 100% VALUE WITH GUARANTY. Buy, sell, or rent vehicles of all types, Real estate,  motorcycles, trucks, electronics, gadgets, home and office accessories, constructions, medicals, agric and food, fashion, buses and search for your dream job on Lata.ng.  Explore a diverse range of products and connect with a vibrant community of sellers and buyers.`;

export const mainMetaKeywords = `cars, motorcycles, trucks, buses, vehicles, Honda, benz, toyota, jeep, car, lexus, camry, kia, tesla, range rover, toshiba, prado, Ford Focus, Nissan, Altima, Hyundai, Elantra, Chevrolet, Malibu, Volkswagen, Golf
,Mazda3, Subaru, Impreza, Kia,  Optima, Toyota Corolla, Honda Accord, Ford Fusion, Nissan Sentra, Hyundai, Sonata, Chevrolet Cruze, Volkswagen, Jetta, Mazda6, Subaru Legacy, Kia Forte, Mercedes-Benz S-Class,
BMW 7 Series,
Audi A8,
Lexus LS,
Jaguar XJ,
Tesla Model S,
Porsche Panamera,
Rolls-Royce Phantom,
Bentley Continental GT,
Maserati Quattroporte,
Aston Martin DB11,
Cadillac CT6,
Lincoln Continental,
Genesis G90,
Infiniti Q70,
Acura RLX,
Volvo S90,
Land Rover Range Rover,
Alfa Romeo Giulia,
BMW 6 Series Gran Coupe buy, sell, rent, Lata.ng,
real estate, homes, apartments, land, commercial properties,Real estate
Property for sale,
Homes for sale,
Apartments for rent,
Commercial properties,
Residential properties,
Land for sale,
Investment properties,
Luxury homes,
Affordable housing,
Condos for sale,
Vacation rentals,
Real estate listings
Property management,
Real estate agent,
House hunting,
Buy property,
Sell property,
Rent property,
Property market trends,
Property valuation,
Property investments,
Rental properties,
New construction homes, duplex, bungalow, c of o, R of o, FCDA, bedroom, affordable house, affordable land,
Housing market analysis, buy, sell, rent, Lata.ng
Property,

Keywords, property, land, houses, apartments, buy, sell, rent, Lata.ng
fashion, clothes, shoes, bags, accessories,Fashion trends,
Clothing,
Apparel,
Fashion accessories,
Designer clothing,
Fashion brands,
Women's fashion,
Men's fashion,
Kids' fashion,
Fashion style,
Fashionable outfits,
Fashion tips,
Fashion inspiration,
Fashionista,
Street style,
Sustainable fashion,
Vintage clothing,
Fashion industry,
Fashion bloggers,
Fashion influencers,
Fashion magazines,
Fashion show,
Fashionable footwear,
Fashionable accessories,
Fashion design , suits, gown, children wears, ladies suit, buy, sell, Lata.ng,
furniture, beds, sofas, tables, chairs, Furniture,
Home furniture,
Modern furniture,
Contemporary furniture,
Wood furniture,
Upholstered furniture,
Bedroom furniture,
Living room furniture,
Dining room furniture,
Outdoor furniture,
Office furniture,
Furniture design,
Furniture styles,
Furniture trends,
Furniture shopping,
Furniture store,
Furniture sale,
Furniture deals,
Custom furniture,
Affordable furniture,
Luxury furniture,
Vintage furniture,
Rustic furniture,
Minimalist furniture, cabinet, kitchen cabinet, TV console, cushing, tables, reading table, work station,
Space-saving furniture, buy, sell, Lata.ng, home accessories, curtains, rugs, lamps, paintings,Home accessories,
Decorative accents,
Interior décor,
Home decor ideas,
Home styling,
Wall art,
Throw pillows,
Vases,
Candle holders,
Picture frames,
Rugs and carpets,
Tableware,
Cushions,
Decorative mirrors,
Plant pots,
Decorative baskets,
Clocks,
Curtains and drapes,
Lighting fixtures,
Ornaments ,buy, sell, Lata.ng,
agric, foods, fruits, vegetables, grains, livestock, Agriculture,
Farming,
Organic farming,
Sustainable agriculture,
Crop cultivation,
Livestock farming,
Agricultural products,
Fresh produce,
Farm-to-table,
Farm-fresh foods,
Food production,
Food supply,
Food processing,
Farm markets,
Agriculture technology,
Agricultural equipment,
Dairy products,
Poultry farming,
Crop yields,
Agricultural sustainability,
Farm management,
Agricultural practices,
Food distribution,
Agricultural innovation,
Agricultural trade, fresh fruits, bulk fruits, food stuff, fresh tomatoes, nigeria rice, foreign rice, buy, sell, Lata.ng,
drinks, alcohol, soft drinks, juices, buy, sell, Lata.ng,
books, textbooks, novels, children's books, motivational books, inspirational books, spiritual books, american books, nigeria books, history, power books, buy, sell, Lata.ng,
education, tutors, courses, resources, materials, buy, sell, rent, hire,
jobs, full-time, part-time, freelance, remote jobs,
electronics, TVs, computers, radio, amplifier, home theatre, speakers, woofers, keyboad, microphones, wires, bulbs and lights, AC, cooling systems, fans, samsung, LG, plasma TV, tiger generator, generators, solar, solar panel, energy saving, cooker, electric gas, smartphones, iphones, android , macbook, windows,  buy, sell, Lata.ng , gadgets, phones, smartwatches, fitness trackers, tablets,Gadgets,
Electronics,
Tech gadgets,
Mobile phones,
Smartphones,
Cell phones,
Phone accessories,
Phone cases,
Mobile accessories,
Gadgets and gizmos,
Wearable devices,
Bluetooth gadgets,
High-tech gadgets,
Latest gadgets,
Tech accessories,
Tablet devices,
Tech innovations,
Mobile apps,
Tech reviews,
Gadget deals, buy, sell, 
rentals, apartments, houses, cars, buy, sell, Lata.ng, sell, buy, I want to sell, I want to buy, where can I buy, which platform is, which is the best e-commerce, best place to sell, where to sell properties, where to sell cars, where to buy wedding gown, where to buy land, duplex, where to find anything, wedding, dresses, flowers, decorations,Wedding planning,
Wedding decorations,
Wedding ideas,
Wedding themes,
Wedding ceremony,
Wedding reception,
Bridal shower,
Wedding venue,
Wedding flowers,
Wedding centerpieces,
Wedding décor,
Wedding table settings,
Wedding accessories,
Wedding invitations,
Wedding party,
Wedding photography,
Wedding inspiration,
Wedding colors,
Wedding trends,
Wedding favors, buy, rent, sell, hire, 
Professional services,
Expert solutions,
Tailored services,
Quality services,
Industry experts,
Service offerings,
Client satisfaction,
Consulting services,
Digital marketing services,
Business solutions,
Customized services,
Expertise,
Reliable services,
Trusted professionals,
Service providers,
Skillful team,
Specialized solutions,
Consultation,
Service excellence,
Business support,
architecture, drawings, designing, construction service, buy, sell, 
Trucks and heavy equipment,
Heavy machinery,
Construction vehicles,
Commercial trucks,
Industrial equipment,
Logistics vehicles,
Heavy-duty vehicles,
Machinery solutions,
Reliable trucks,
Equipment rentals,
Construction machinery,
Heavy equipment sales,
Commercial vehicle options,
Industrial machinery,
Truck fleet,
Machinery suppliers,
Vehicle selection,
Construction projects,
Logistics solutions,
Business equipment, sell, buy, rent, hire, Lata.ng
Keyword, visa, passport, abuja, lagos, Nigeria, kogi, porthacourt, rivers,
Visa and passport services,
Travel documentation,
Visa processing,
Passport application,
Travel preparation,
Visa assistance,
Passport services,
Expedited visas,
Passport renewal,
Travel documents,
Visa experts,
Passport consultants,
Visa application, sell, buy, service, 

Best place to sell and buy,
Seamless buying and selling,
Secure platform,
User-friendly marketplace,
Diverse product range,
Vibrant community,
Trusted buying and selling,
Hassle-free transactions,
Top-notch selling experience,
Ultimate marketplace,
Reliable platform,
Efficient buying process,
Quality products,
Trusted sellers,
Secure transactions,
Buyer satisfaction,
Seller convenience,
Premium marketplace,
Convenient online buying,
Reliable selling platform, buy, sell, rent, Lata.ng, where to sell in abuja, where to sell in lagos, bungalow, service provider, where to get sales results, professional marketer, online experts, ads experts, social media experts, best location in abuja, jiji.ng,  best location in lagos, best location in Nigeria, white suit, blue suits, green suits, ladies suits, ladies wears, children wears, children toys, toy cars, babies wears, baby cars, cap, gold, premium, silver, wrist watch, gold watch, golden ring, rings, plumbers, plumbing, trainings, services, factories, oil and gas, flights, location, platform, lata.ng, lata, tala, peter obi, celebrity, sports, bbn, church, religion, tech, news, tinubu, apc, labour party, movies, courses, fintech, platforms, homes, business, market, place, customes, hall, events, choir, music, traditional, lata.ng`;
